### ISSUE TITLE
Update interval 5M, but no location update for 5 hours

### ISSUE THREAD

**Issue by w1Ngx** [eifinger/hass-weenect#318]
Hi,

i installed the weenect integration some days ago and since then I am wondering why it’s not showing the gps location accurate at any time, while the weenect act does. HA somehow updates the location randomly after 5 hours+

Log Details (ERROR):
Logger: homeassistant
Source: util/dt.py:192
First occurred: 10:47:41 AM (1104 occurrences)
Last logged: 8:18:54 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 473, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weenect/sensor.py", line 148, in native_value
    return dt.parse_datetime(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 192, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument must be str

**Comment by w1Ngx** [comment]
Is this integration dead?

**Comment by eifinger** [comment]
I have just release https://github.com/eifinger/hass-weenect/releases/tag/v3.2.3. Please upgrade to this version, enable debug logs by following https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics and upload them here. I need this information to determine what exactly the issue is.

**Comment by w1Ngx** [comment]
ok, just ran the debug logging and captured it multiple times, hope this helps. 
Thanks for your efforts!

[home-assistant_weenect_2023-10-05T10-06-09.105Z.log](https://github.com/eifinger/hass-weenect/files/12817096/home-assistant_weenect_2023-10-05T10-06-09.105Z.log)

**Comment by eifinger** [comment]
The newest release should fix the issues you reported. Thank you for that!
