### ISSUE TITLE
Unable to install package aioweenect==1.1.2: ERROR: Cannot install aioweenect==1.1.2 because these package versions have conflicting dependencies

### ISSUE THREAD

**Issue by Timokirch** [eifinger/hass-weenect#378]
Hi, 

unfortunately i can't setup the integration due to an error while adding the device to HA.
<img width="584" alt="image" src="https://github.com/user-attachments/assets/71f3f9d3-b77c-4590-bf5e-17bc3ce88e9b">

```
Logger: homeassistant.util.package
Quelle: util/package.py:123
Erstmals aufgetreten: 23:21:30 (3 Vorkommnisse)
Zuletzt protokolliert: 23:21:34

Unable to install package aioweenect==1.1.2: ERROR: Cannot install aioweenect==1.1.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
``` 

```
Logger: aiohttp.server
Quelle: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
Erstmals aufgetreten: 23:21:34 (1 Vorkommnisse)
Zuletzt protokolliert: 23:21:34

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1267, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1287, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1423, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2851, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2828, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 563, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await future
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 269, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 307, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for weenect not found: ['aioweenect==1.1.2'].
``` 

Kind Regards and thanks for the help on advance

Timo

**Comment by Timokirch** [comment]
Update: When installing v 5.1.1 it works.

**Comment by Timokirch** [comment]
Hi, I just came across this wonderful integration yesterday evening and tried to install the latest version. The logs did not come from an upgrade. It was a greenfield setup. I can try and update to the latest version today.

Kind regards 
Timo

**Comment by Timokirch** [comment]
Even with an update i get the same errors.

**Comment by m1ndgames** [comment]
Hey,
i just found out about the integration, and also wanted to report the same issue given by @Timokirch 

Timo you installed 5.1.1 manually right? Cause i cant see a version pulldown in the HACS installer UI.

**Comment by m1ndgames** [comment]
> > Timo you installed 5.1.1 manually right? Cause i cant see a version pulldown in the HACS installer UI.
> 
> If you have the 5.1.2 in your HACS, click on the 3 dots and then "Redownload". There will be a dropdown of releases. https://hacs.xyz/docs/faq/select_version/

Oh, it seems like this is a general error on my side. I dont have the pull down in any HACS extension.

I will sort it out...

**Comment by mathieupotier** [comment]
Retrying install this morning and still got the error:

Enregistreur: homeassistant.util.package
Source: util/package.py:123
S'est produit pour la première fois: 09:09:10 (3 occurrences)
Dernier enregistrement: 09:09:18

Unable to install package aioweenect==1.1.2: ERROR: Cannot install aioweenect==1.1.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by eifinger** [comment]
Can you please provide me with more logs? The logs you send so far mentioned conflicting dependencies. I need to know which ones are conflicting

**Comment by mathieupotier** [comment]
Here are more logs from HA...

------

Enregistreur: homeassistant.setup
Source: setup.py:271
S'est produit pour la première fois: 09:09:18 (1 occurrences)
Dernier enregistrement: 09:09:18

Setup failed for custom integration 'weenect': Requirements for weenect not found: ['aioweenect==1.1.2'].

------

Enregistreur: homeassistant.util.package
Source: util/package.py:123
S'est produit pour la première fois: 09:09:10 (3 occurrences)
Dernier enregistrement: 09:09:18

Unable to install package aioweenect==1.1.2: ERROR: Cannot install aioweenect==1.1.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

-----

I don't have more than this for now, but seems to be aioweenect the source of the problem.

But here are some information about the running instances:

![image](https://github.com/user-attachments/assets/7c32c308-2231-4ee4-aa5c-3bcbae542c19)

![image](https://github.com/user-attachments/assets/4587c667-a38d-417e-9c09-5db865586456)

**Comment by eifinger** [comment]
Version 1.1.4 should fix the issue. Please try it

**Comment by mathieupotier** [comment]
Seems ok now... thanks 😉
